### ISSUE TITLE
Update the post

### ISSUE THREAD

**Issue by notiont** [leojuriolli7/t3-blog#38]
Dear, 
I am so glad you share great community platform :)
I perceived that updating post is not working myside after creating the post.
I do not know it is WIP though.
Please kindly review the issue.
Have a grest one! 

By any chance is there any plan to add iframe in the post? 
Thank you.

**Comment by leojuriolli7** [comment]
Thank you for noticing this, it should be fixed now.

**Comment by masapasa** [comment]
Hi @leojuriolli7 @notiont 
I think I am getting wrong s3 urls. It should be https://t3-blog.s3.amazonaws.com/
But I am getting this erro. POST https://t3-blog.s3.sa-east-1.amazonaws.com/ net::ERR_CONNECTION_RESET
I highly appreciate any help
